name: Make github pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      
      - name: Get node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: npm ci
        run: npm ci
      
      - name: build
        run: npm run generate
      
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: public
          FOLDER: .output/public
      
